create table books_payments(Books_Payments_Id varchar2(20) primary key,
				Book_Issue_To_Student varchar2(20) references book_issued_to_student(Book_Issue_To_Student),
				Term_Id varchar2(20) references terms(Term_Id),
				Book_Id varchar2(20) references year_wise_book_master(Book_Id),
				Book_Fee_Amount number(7,2),
				Fee_To_Be_Paid_Before varchar2(20),
				Student_No varchar2(20) references student(Student_No),
				Fee_Amount number(7,2),
				Fee_Paid_Date date,
				Fee_Penalty number(7,2),
				Fee_Paid_Mode varchar2(20),
				Fee_Paid_By varchar2(20),
				Fee_Received_By varchar2(20) references staff(Staff_Id),
				Fee_receipt_Id varchar2(20),
				Created_By varchar2(20),
				Creation_Date date,
				Last_Updated_By varchar2(20),
				Last_updation_Date date);