create table extra_curr_act_payments(ECAP_Id varchar2(20) primary key,
					Term_Id varchar2(10) references terms(Term_Id),
					Sports_Id varchar2(20) references sports_master(Sports_Id),
					Extra_Curr_Fee_Amount number(7,2),
					Fee_To_Be_Paid_Before varchar2(10),
					Student_No varchar2(20) references student(Student_No),
					Fee_Amount number(7,2),
					Fee_Paid_Date date,
					Fee_Penalty number(7,2),
					Fee_Paid_Mode varchar2(20),
					Fee_Paid_By varchar2(20),
					Fee_Received_By varchar2(20) references staff(Staff_Id),
					Fee_Receipt_Id number(5),
					Created_By varchar2(20),
					Creation_Date date,
					Last_Updated_By varchar(20),
					Last_Updation_Date date);