create table library_payments(Lib_Payment_Id varchar2(20) primary key,
				Library_Id varchar2(20) references library_master(Library_Id),
				LIOD_Id varchar2(20) references library_in_out_details(LIOD_Id),
				Library_Fee_Amount number(7,2),
				Fee_To_Be_Paid_Before varchar2(20),
				Student_No varchar2(20) references student(Student_No),
				Fee_Amount number(7,2),
				Fee_Paid_Date date,
				Fee_Penalty number(7,2),
				Fee_Paid_Mode varchar2(20),
				Fee_Paid_By varchar2(20),
				Fee_Received_By varchar2(20) references staff(Staff_Id),
				Fee_Receipt_Id varchar2(10),
				Created_By varchar2(20),
				Creation_Date date,
				Last_Updated_by varchar2(20),
				Last_Updation_Date date);