create table staff_salary(Staff_Salary_Id varchar2(20) primary key,
				Staff_Id varchar2(20) references staff(Staff_Id),
				Annual_Salary number(9,2),
				Year varchar2(20),
				Month varchar2(20),
				Gross_Sal number(9,2),
				Total_Deductions number(9,2),
				Net_Salary number(9,2),
				Income_Tax_Deducted number(9,2),
				Income_Tax_Amount number(9,2),
				Salary_Credited_To_Account varchar2(20),
				Credited_Mode varchar2(20),
				Credit_Initiated_By varchar2(20),
				Credit_Initiated_Date date,
				Additional_Comments varchar2(40),
				Created_By varchar2(20),
				Creation_Date date,
				Last_Updated_By varchar2(20),
				Last_Updation_Date date);