create table teachers(Teacher_Id varchar2(10) primary key,
			Teacher_Name varchar2(20) not null,
			DOB date,
			DOJ date,
			Gender char(1) check(Gender in('M','F')),
			Father_Name varchar2(20),
			Mother_Name varchar2(20),
			Spouse_Name varchar2(20),
			Grade char(1),----dought
			Insurance_Name varchar2(20),
			Insurance_Premium number(9,2),
			Insurance_Valid_Till date,
			Insured_amount number(9,2),
			Insurance_Number varchar2(20),
			Total_Experience number(5),
			Subject_Matter_Expert varchar2(20),
			Value_Additions varchar2(20),
			If_Refferenced_By varchar2(20),
			Interviewed_By varchar2(20),
			Interviewed_Date date,
			PAN_Card_Number varchar2(20),
			Bank_Account_Number number(15),
			Address varchar2(30),
			Email_Id varchar2(30),
			Mobile number(10) check(length(Mobile)=10) not null,
			Emergency_Contact varchar2(20),
			Emergency_Contact_Mobile number(10) check(length(Emergency_Contact_Mobile)=10) not null,
			Previous_Organisation varchar2(20),
			Previous_Org_Annual_Income number(9,2),
			Created_By varchar2(20),
			Creation_Date date,
			Last_Updated_By varchar2(20),
			Last_Updation_Date date);