create table teachers(Teacher_Id varchar2(20) constraints pk_teachers primary key,
			Teacher_Name varchar2(20) not null,
			DOB date,
			DOJ date,
			Gender char(6) check(Gender in('M','F','m','f','male','female','MALE','FEMALE','Female','Male')),
			Father_Name varchar2(50),
			Mother_Name varchar2(50),
			Spouse_Name varchar2(50),
			Grade varchar2(20),
			Insurance_Name varchar2(50),
			Insurance_Premium number(11,2),
			Insurance_Valid_Till date,
			Insured_amount number(11,2),
			Insurance_Number varchar2(40),
			Total_Experience number(5),
			Subject_Matter_Expert varchar2(30),
			Value_Additions varchar2(50),
			If_Refferenced_By varchar2(50),
			Interviewed_By varchar2(50),
			Interviewed_Date date,
			PAN_Card_Number varchar2(50),
			Bank_Account_Number number(30),
			Address varchar2(80),
			Email_Id varchar2(50),
			Mobile number(10) check(length(Mobile)=10) not null,--no need to add country code
			Emergency_Contact varchar2(50),
			Emergency_Contact_Mobile number(10) check(length(Emergency_Contact_Mobile)=10) not null,
			Previous_Organisation varchar2(50),
			Previous_Org_Annual_Income number(11,2),
			Created_By varchar2(50),
			Creation_Date date,
			Last_Updated_By varchar2(50),
			Last_Updation_Date date);
