create table term_wise_fee_payments(TWFP varchar2(20) primary key,
					Term_Id varchar2(20) references terms(Term_Id),
					Fee_Id varchar2(20) references fee_master(Fee_Id),
					Term_Fee_To_Be_Paid_Before varchar2(5) check(Term_Fee_To_Be_Paid_Before in('yes','no')),
					Student_NO varchar2(20) references student(Student_No),
					Fee_Amount number(7,2),
					Fee_Paid_Date date,
					Fee_penalty number(7,2),
					Fee_Paid_Mode varchar2(10),
					Fee_Paid_By varchar2(20),
					Fee_Received_By varchar2(20) references staff(Staff_Id),
					Fee_Receipt_Id varchar(5),
					Created_By varchar2(20),
					Creation_Date date,
					Last_Updated_By varchar2(20),
					Last_Updation_Date date);