create table transport_fee_payments(TR_Fee_Payment_Id varchar2(20) primary key,
					TR_Enroll_Roaster_Id varchar2(20) references transport_enrollments_roaster(TR_Enroll_Roaster_Id),
					Transport_Route_Id varchar2(20) references transport(Transport_Route_Id),
					Transport_Fee_Amount number(7,2),
					Fee_To_Be_Paid_Before varchar2(20),
					Term_Id varchar2(20) references terms(Term_Id),
					Student_No varchar2(20) references student(Student_No),
					Fee_Amount number(7,2),
					Fee_Paid_Date date,
					Fee_Penalty number(7,2),
					Fee_Paid_Mode varchar2(20),
					Fee_Paid_By varchar2(20),
					Fee_Received_By varchar2(20) references staff(Staff_Id),
					Fee_Receipt_Id varchar2(10),
					Created_By varchar2(20),
					Creation_Date date,
					Last_Updated_by varchar2(20),
					Last_Updation_Date date);