create table year_wise_book_master(Book_Id varchar2(20) primary key,
					Book_Name varchar2(20),
					Year number(4) check(Year between 2000 and 2100),
					Month number(2) check(Month between 1 and 12),
					Day number(2) check(Day between 1 and 31),
					Author varchar2(20),
					REvision varchar2(20),
					If_Purchased_By varchar2(20),
					If_Purchased_Date date,
					Added_To_Library_By varchar2(20),
					Added_To_Library_Date date,
					Library_Rack_no number(3),
					Library_Id varchar2(20) references library_master(Library_Id),
					Price number(7,2),
					Quantity number(3),
					Created_By varchar2(20),
					Creation_Date date,
					Last_Updated_By varchar(20),
					Last_Updation_Date date);
