create table class_wise_sports(CWS_Id varchar2(20) constraints CWS_pk primary key,
				Sports_Id varchar2(20) references sports_Master(Sports_Id),
				Class_Id varchar2(20) references class(Class_Id),
				Allocation_To_Section_By varchar2(50),
				Allocation_To_Section_Date date,
				Change_Notes varchar2(80),
				Change_Date date,
				Created_By varchar2(50),
				Creation_Date date,
				Last_Updated_by varchar2(50),
				Last_Updation_Date date);