create table library_in_out_details(LIOD_Id varchar2(20) constraints Library_INOUT_pk primary key,
					Library_Id varchar(20) references library_master(Library_Id),
					Book_Issued_To_Student varchar2(20) references student(Student_No),
					Book_Issued_By varchar2(50),
					Book_Issud_To varchar2(50),
					Book_Return_Due_Date date,
					Actual_Book_Returned_Date date,
					Book_Collected_By varchar2(20) references staff(Staff_Id),
					Created_By varchar2(50),
					Creation_Date date,
					Last_Updated_by varchar2(50),
					Last_Updation_Date date);