create table sports_participation(Sports_Part_Id varchar2(20) constraints SP_ID_pk primary key,
					Sports_Id varchar2(20) references sports_master(Sports_Id),
					CWS_Id varchar2(20) references class_wise_sports(CWS_Id),
					Student_No varchar2(10) references student(Student_No),
					Participation_Date date,
					Prize_Name varchar2(50),
					Prize_Date date,
					Prize_Given_By varchar2(50),
					Prize_For varchar2(50),
					Coach_Comments varchar2(100),
					Created_By varchar2(50),
					Creation_Date date,
					Last_Updated_By varchar(50),
					Last_Updation_Date date);