create table teacher_salary(Teacher_Salary_Id varchar2(20) constraints teacher_sal_pk primary key,
				Teacher_Id varchar2(20) references teachers(Teacher_Id),
				Annual_Salary number(11,2),
				Year varchar2(20),
				Month varchar2(20),
				Gross_Sal number(11,2),
				Total_Deductions number(11,2),
				Net_Salary number(11,2),
				Income_Tax_Deducted number(11,2),
				Income_Tax_Amount number(11,2),
				Salary_Credited_To_Account varchar2(30),
				Credited_Mode varchar2(50),
				Credit_Initiated_By varchar2(50),
				Credit_Initiated_Date date,
				Additional_Comments varchar2(100),
				Created_By varchar2(50),
				Creation_Date date,
				Last_Updated_By varchar2(50),
				Last_Updation_Date date);