create table transport(Transport_Route_Id varchar2(20) constraints transport_pk primary key,
			Route_Id varchar2(20),Route_Name varchar2(20),
			Route_Planned_Month_Year varchar2(20),
			Route_Valid_Till date,
			Route_Coordinator varchar2(50),
			Route_Grievance_Officer varchar2(50),
			Route_Grievance_Ph_No number(10) check(length(Route_Grievance_Ph_No)=10),
			Route_Vehicle_Number_List Vehicle_List,
			Route_Distance number(5),
			Route_TAT_Estimation varchar2(20),
			Route_TAT_Estimation_By varchar2(50),
			Route_Start_Point varchar2(30),
			Route_End_Point varchar2(30),
			Route_Prime_Driver varchar2(20) references staff(Staff_Id),
			Created_By varchar2(50),
			Creation_Date date,
			Last_Updated_By varchar(50),
			Last_Updation_Date date);