create table year_wise_book_master(Book_Id varchar2(20) constraints year_book_pk primary key,
					Book_Name varchar2(50),
					Year number(4) constraints year_book_check1 check(Year between 2000 and 2100),
					Month number(2) constraints year_book_check2 check(Month between 1 and 12),
					Day number(2) constraints year_book_check3 check(Day between 1 and 31),
					Author varchar2(50),
					Revision varchar2(50),
					If_Purchased_By varchar2(50),
					If_Purchased_Date date,
					Added_To_Library_By varchar2(50),
					Added_To_Library_Date date,
					Library_Rack_no varchar2(20),
					Library_Id varchar2(20) references library_master(Library_Id),
					Price number(11,2),
					Quantity number(3),
					Created_By varchar2(50),
					Creation_Date date,
					Last_Updated_By varchar(50),
					Last_Updation_Date date);